import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "./components/sidebar";
import ReduxProvider from "@/redux/provider";
import NextThemeProvider from "./providers/themeProvider/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TaskMaster",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" />
      </head>
      <body className={inter.className}>
        <ReduxProvider>
          <NextThemeProvider>
            <div className={"wrapper"}>
              <Sidebar />
              <div className={"wrapperRight"}>{children}</div>
            </div>
          </NextThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
