"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "./components/sidebar";
import ReduxProvider from "@/redux/provider";
import { ThemeProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Project management",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <ThemeProvider>
            <div className={"wrapper"}>
              <Sidebar />
              <div className={"wrapperRight"}>{children}</div>
            </div>
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
